CREATE TABLE `routes` (
	`id` INT(10) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(200) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`map` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`map_id` INT(10) NOT NULL,
	`length` FLOAT NULL DEFAULT NULL,
	`elevation` FLOAT NULL DEFAULT NULL,
	`lead_in` FLOAT NULL DEFAULT NULL,
	`restriction` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`badge_xp` INT(10) NULL DEFAULT NULL,
	`completed` TINYINT(1) NOT NULL DEFAULT '0',
	`created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`) USING BTREE,
	UNIQUE INDEX `name` (`name`) USING BTREE,
	INDEX `map_id` (`map_id`) USING BTREE,
	CONSTRAINT `routes_ibfk_1` FOREIGN KEY (`map_id`) REFERENCES `worlds` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
AUTO_INCREMENT=190
;
